variables:
  # All variables of this project start with "pd_", by convention.
  hq_project: HelloQt

jobs:
- job: Windows_64
  variables:
    hq_configuration: Release
    hq_platform: x64
    hq_bit: 64
    hq_build_dir: build$(hq_bit)
  timeoutInMinutes: 0
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: CacheBeta@0
    inputs:
      key: $(Agent.OS) | vcpkg | 20190827
      path: $(VCPKG_INSTALLATION_ROOT)
      cacheHitVar: CACHE_VCPKG_RESTORED
      displayName: Cache vcpkg libraries  
  - script: |
      cd /d C:\vcpkg
      git log -1
      git pull
      git log -1
      call .\bootstrap-vcpkg.bat
      set VCPKG_DEFAULT_TRIPLET=x64-windows
      C:\vcpkg\vcpkg.exe install qt5
    displayName: git pull vcpkg, bootstrap-vcpkg, install qt
    condition: ne(variables.CACHE_RESTORED, 'true')
  - script: |
      C:\vcpkg\vcpkg.exe integrate install
    displayName: vcpkg integrate
  - task: CMake@1
    displayName: 'CMake Generate'
    inputs:
      cmakeArgs: -G "Visual Studio 15 2017 Win64" -S .. "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
      workingDirectory: "$(HQ_BUILD_DIR)"
  - task: MSBuild@1
    displayName: 'MSBuild'
    inputs:
      solution: '$(HQ_BUILD_DIR)/ALL_BUILD.vcxproj'
      configuration: $(HQ_CONFIGURATION)
      msbuildArguments: /p:VcpkgEnabled=true
  - script: |
      %HQ_BUILD_DIR%\%HQ_CONFIGURATION%\%HQ_PROJECT%.exe
    displayName: Run it now
